image: "continuumio/miniconda3:4.8.2"

before_script:
  - apt-get update
  - apt-get install -y libxml2-utils

stages:
  - Test
  - CreateReleasePackageLite

IntegrationTest:
  stage: Test
  script:
    - bash conda-requirements.sh
    - pip install twine
    - python setup.py install
    - pip install -r requirements-dev.txt
    - python setup.py sdist
    - nosetests -sx
    - pytest --junitxml=test_metadata_extractor.xml test
    - nosetests -c .noserc -q --cover-html-dir=build --cover-html
    - coverage report -m
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: '$CI_MERGE_REQUEST_ID'

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: test*.xml

CreateReleasePackageLite:
  stage: CreateReleasePackageLite
  script:
   - python create_deploy_release_package.py
#  rules:
#   - if: '$CI_COMMIT_REF_NAME == "master"'
#   - if: '$CI_MERGE_REQUEST_ID'

  artifacts:
    name: "${CI_PROJECT_NAME}_lite_${CI_COMMIT_SHA}"
    paths:
      - package.zip
    expire_in: never

