image: "python:3.7"

before_script:
  - apt-get update
  - apt-get install -y libxml2-utils

stages:
  - Test

IntegrationTest:
  stage: Test
  script:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.2-Linux-x86_64.sh
    - bash Miniconda3-py37_4.8.2-Linux-x86_64.sh -b -p
    - export PATH=$PATH:/root/miniconda3/bin
    - conda init bash
    - source /root/.bashrc
    - conda activate base
    - bash conda-requirements.sh
    - conda install pip
    - pip install twine
    - python setup.py install
    - pip install -r requirements-dev.txt
    - python setup.py sdist
    - ls -al /builds/ghrc-cloud/metadata-extractor/test/fixtures/lpvex_SHP_Aranda_ODM_u100915_00.txt
    - nosetests -sx
    - ls -al /builds/ghrc-cloud/metadata-extractor/test/fixtures/lpvex_SHP_Aranda_ODM_u100915_00.txt
    - pytest --junitxml=test_metadata_extractor.xml test
    - nosetests -c .noserc -q --cover-html-dir=build --cover-html
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: test*.xml
