image: "continuumio/miniconda3:4.8.2"

before_script:
  - apt-get --allow-releaseinfo-change update
  - apt-get install -y libxml2-utils

stages:
  - Test

IntegrationTest:
  stage: Test
  script:
    - bash conda-requirements.sh
    - pip install twine
    - python setup.py install
    - pip install -r requirements-dev.txt
    - python setup.py sdist
    - nosetests -sx
    - pytest --junitxml=test_metadata_extractor.xml test
    - nosetests -c .noserc -q --cover-html-dir=build --cover-html
    - coverage report -m

  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: test*.xml

CreateLambdaArtifact:
  stage: .post
  script:
    - python create-artifact.py
  artifacts:
    name: "${CI_PROJECT_NAME}_lambda_artifact_${CI_COMMIT_SHA}"
    paths:
#      - mdx_lambda_artifact.zip
      - mdx_lambda_artifact/.
    expire_in: never
