image: "conda/miniconda3"

before_script:
  - apt-get update
  - apt-get install -y libxml2-utils 

stages:
  - Test

IntegrationTest:
  stage: Test
  script:
    - conda init bash
    - source /root/.bashrc
    - conda activate mdx
    - conda env update -n mdx--file=environment.yaml
    - pip install twine
    - python setup.py install
    - pip install -r requirements-dev.txt
    - python setup.py sdist
    - nosetests -sx
    - pytest --junitxml=test_metadata_extractor.xml test
    - nosetests -c .noserc -q --cover-html-dir=build --cover-html
    - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      junit: test*.xml
