from .process_globalir import ExtractGlobalirMetadata
from .process_nalma import ExtractNalmaMetadata
from .process_nalmanrt import ExtractNalmanrtMetadata
from .process_nalmaraw import ExtractNalmarawMetadata